#In Class Assignment: Matrices - Week 3

In [ ]:
import numpy as np

Define the matricies as numpy arrays

In [ ]:
A = np.array([[2,4,-7],[3,-3,0],[1,7,5]])
print("A:\n", A, "\n")

B = np.array([[2,4],[3,-3],[1,7]])
print("B:\n", B, "\n")

C = np.array([[-1,1],[1,-1]])
print("C:\n", C, "\n")

D = np.array([[2,0],[-3,6]])
print("D:\n", D)

A:
 [[ 2  4 -7]
 [ 3 -3  0]
 [ 1  7  5]] 

B:
 [[ 2  4]
 [ 3 -3]
 [ 1  7]] 

C:
 [[-1  1]
 [ 1 -1]] 

D:
 [[ 2  0]
 [-3  6]]


Multiply 
A
 by 2.5

In [ ]:
New_A = A*2.5

print("(2.5)A:\n",New_A)

(2.5)A:
 [[  5.   10.  -17.5]
 [  7.5  -7.5   0. ]
 [  2.5  17.5  12.5]]


Evaluate the product of 
C
⋅
A
Did you get an error? Do you know why? (Hint: look at the dimensions of the matrix)

In [ ]:
CA = np.matmul(C, A)
print(CA)

# These matrices do not have the same dimensions so you cannot multiply/add them

ValueError: ignored

Evaluate the product of 
C
⋅
D
 and then 
D
⋅
C
. Do you get the same results?
different answers CD != DC

In [ ]:
CD = np.matmul(C, D)
print("CD:\n",CD, "\n")

DC = np.matmul(D, C)
print("DC:\n",DC)

CD:
 [[-5  6]
 [ 5 -6]] 

DC:
 [[-2  2]
 [ 9 -9]]


Find the transpose of B

In [ ]:
B_T = B.T
print("Transpose of B:\n", B_T)

Transpose of B:
 [[ 2  3  1]
 [ 4 -3  7]]


Add C+D

In [ ]:
sum_CD = C + D
print("C+D:\n",sum_CD)

C+D:
 [[ 1  1]
 [-2  5]]


Compute the determinate of C

In [ ]:
detC = np.linalg.det(C)
print("Determinate of C:", detC)

Determinate of C: 0.0


Compute the determinate of A

In [ ]:
detA = np.linalg.det(A)
print("Determinate of A:", detA)

Determinate of A: -257.9999999999998
