# Week 3 2nd In-Class Assignment

Find the eigenvalues and eigenvectors for the equation:

(
A
→
−
λ
I
→
)
v
→
=
0
,
where 
v
→
 are the eigenvectors and 
λ
 is the eigenvalues



In [ ]:
import numpy as np
import matplotlib.pyplot as plt

#define matrix
#find eigenvaules and eigenvectors

a = np.array([[11, -1, 0], [-1, 12, -1], [0, -1, 11]])
b,c = np.linalg.eig(a)
print('E-value:\n', b)
print('E-vector:\n', c)

E-value:
 [13. 11. 10.]
E-vector:
 [[-4.08248290e-01 -7.07106781e-01  5.77350269e-01]
 [ 8.16496581e-01  4.32041765e-16  5.77350269e-01]
 [-4.08248290e-01  7.07106781e-01  5.77350269e-01]]
